{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axelar-node.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axelar-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  {{- if .Values.secrets.keyringPassword }}
  keyring-password: {{ .Values.secrets.keyringPassword | b64enc | quote }}
  {{- else }}
  keyring-password: ""
  {{- end }}
  {{- if eq .Values.deploymentType "validator" }}
  {{- if .Values.secrets.tofndPassword }}
  tofnd-password: {{ .Values.secrets.tofndPassword | b64enc | quote }}
  {{- else }}
  tofnd-password: ""
  {{- end }}
  {{- if .Values.secrets.validatorMnemonic }}
  validator-mnemonic: {{ .Values.secrets.validatorMnemonic | quote }}
  {{- end }}
  {{- if .Values.secrets.tofndMnemonic }}
  tofnd-mnemonic: {{ .Values.secrets.tofndMnemonic | quote }}
  {{- end }}
  {{- if .Values.secrets.tendermintKey }}
  tendermint-key: {{ .Values.secrets.tendermintKey | quote }}
  {{- end }}
  {{- end }}
{{- end }}
